### ISSUE TITLE
While this plugin is enabled, items from player inventory on 1:1 get randomly deleted

### ISSUE THREAD

**Issue by joker-119** [MrMith/ItemStacks#1]
As the title says, when anyone goes through 914 on 1:1, items in their inventory (seems to only affect keycards, medkits, flashlights and coins, but was not throughouly tested) seem to - at random, get removed from their inventory for no reason. 
We have no other plugins that affect player inventory, not even 914HeldItems is installed, nor 914 Custom Recipies

Removal of this plugin promptly put an end to this bug entirely.

**Comment by MrMith** [comment]
I'm having trouble recreating this with any 914 knob setting.
Can you either respond here or message me on discord with a complete list of plugins?

**Comment by joker-119** [comment]
At the time I encountered the issue..
BetterDisarming
DefaultAmmo
Lone079
SCPDiscord
SFs.Later.Join
ToggleTag
stayshut

**Comment by joker-119** [comment]
Didn't mean to close, whoops

**Comment by MrMith** [comment]
Still having trouble recreating. I installed all those plugins excluding SCPDiscord and nothing. 
Can you pm on discord or pastebin your config with all of the personal stuff edited out?

**Comment by MrMith** [comment]
Problem happens with either 914inhand or config options to change class when going through 914.

**Comment by MrMith** [comment]
I have the time to work on this.
Basically just incorporating 914-held-items into this plugin that supports my stacking system.

**Comment by MrMith** [comment]
Fixed in 0ff8893
